# Generated by Django 6.0.7 on 2026-07-20 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan_type', models.CharField(blank=True, max_length=50)),
                ('plan_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('result_type', models.CharField(blank=True, max_length=50)),
                ('result_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('reflection', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_entry_per_user_date')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('focus', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'month'), name='unique_goal_per_user_month')],
            },
        ),
    ]
