# Generated by Django 6.0.7 on 2026-08-03 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_goal', models.CharField(choices=[('5K', '5K'), ('10K', '10K'), ('Half Marathon', 'Half Marathon'), ('Marathon', 'Marathon')], max_length=30)),
                ('goal_date', models.DateField()),
                ('target_time', models.CharField(max_length=20)),
                ('longest_run', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weekly_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pb_5k', models.CharField(blank=True, max_length=20)),
                ('pb_10k', models.CharField(blank=True, max_length=20)),
                ('pb_half_marathon', models.CharField(blank=True, max_length=20)),
                ('pb_marathon', models.CharField(blank=True, max_length=20)),
                ('guide_content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_guides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
